-- Cadastro de clientes e pedidos originados pelo checkout. O telefone
-- normalizado é a identidade única de quem compra sem login.
create extension if not exists pgcrypto;

create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(trim(name)) >= 2),
  phone_normalized text not null unique check (phone_normalized ~ '^55[1-9][0-9](9[0-9]{8}|[2-9][0-9]{7})$'),
  phone_display text not null,
  is_shared_phone boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity unique,
  customer_id uuid not null references public.customers(id) on delete restrict,
  customer_name_snapshot text not null,
  customer_phone_snapshot text not null,
  status text not null default 'received' check (status in (
    'received', 'confirmed', 'preparing', 'out_for_delivery', 'delivered', 'cancelled'
  )),
  delivery_type text not null check (delivery_type in ('entrega', 'retirada')),
  address_snapshot text,
  house_number_snapshot text,
  has_no_house_number boolean not null default false,
  complement_snapshot text,
  neighborhood_snapshot text,
  payment_method text not null,
  change_for text,
  subtotal numeric(12, 2) not null check (subtotal >= 0),
  extras_total numeric(12, 2) not null default 0 check (extras_total >= 0),
  delivery_fee numeric(12, 2) not null default 0 check (delivery_fee >= 0),
  total numeric(12, 2) not null check (total >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  source_product_id text,
  line_type text not null check (line_type in ('product', 'extra')),
  product_name text not null,
  unit_price numeric(12, 2) not null check (unit_price >= 0),
  quantity integer not null check (quantity > 0),
  line_total numeric(12, 2) not null check (line_total >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.customer_name_conflicts (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.customers(id) on delete cascade,
  order_id uuid not null unique references public.orders(id) on delete cascade,
  submitted_name text not null,
  normalized_name text not null,
  status text not null default 'pending' check (status in ('pending', 'corrected', 'ignored', 'shared_phone')),
  resolution text,
  resolved_by uuid references auth.users(id) on delete set null,
  resolved_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists orders_customer_created_at_idx on public.orders(customer_id, created_at desc);
create index if not exists orders_status_created_at_idx on public.orders(status, created_at desc);
create index if not exists order_items_order_id_idx on public.order_items(order_id);
create index if not exists customer_name_conflicts_status_created_at_idx on public.customer_name_conflicts(status, created_at desc);
create index if not exists customer_name_conflicts_customer_id_idx on public.customer_name_conflicts(customer_id);

alter table public.customers enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.customer_name_conflicts enable row level security;

-- A aplicação pública grava pedidos apenas pelo endpoint do servidor, que usa
-- a service role. Não há política pública para leitura de dados pessoais.
